(include "LuTommyInterpreterPart1.rkt")
(require rackunit)
(check-equal? (interpret "test11.txt") "error")
(check-equal? (interpret "test12.txt") "error")
(check-equal? (interpret "test13.txt") "error")
(check-equal? (interpret "test14.txt") "error")
(check-equal? (interpret "test15.txt") "true")
(check-equal? (interpret "test16.txt") 100)
(check-equal? (interpret "test17.txt") "false")
(check-equal? (interpret "test18.txt") "true")
(check-equal? (interpret "test19.txt") 128)
(check-equal? (interpret "test20.txt") 12)