(include "LuTommyInterpreterPart1.rkt")
(require rackunit)
(check-equal? (interpret "test21.txt") 30)
(check-equal? (interpret "test22.txt") 11)
(check-equal? (interpret "test23.txt") 1106)
(check-equal? (interpret "test24.txt") 12)
(check-equal? (interpret "test25.txt") 16)
(check-equal? (interpret "test26.txt") 72)
(check-equal? (interpret "test27.txt") 21)
(check-equal? (interpret "test28.txt") 164)