(include "LuTommyInterpreterPart1.rkt")
;(require rackunit)
;(check-equal? (interpret "test1.txt") 150)
;(check-equal? (interpret "test2.txt") -4)
;(check-equal? (interpret "test3.txt") 10)
;(check-equal? (interpret "test4.txt") 16)
;(check-equal? (interpret "test5.txt") 220)
;(check-equal? (interpret "test6.txt") 5)
;(check-equal? (interpret "test7.txt") 6)
;(check-equal? (interpret "test8.txt") 10)
;(check-equal? (interpret "test9.txt") 5)
;(check-equal? (interpret "test10.txt") -39)